import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Authentication } from "@components/Authentication";
import React from "react";
import { Layout } from "@components/Layout";
import { useSession, useSupabaseClient } from "@supabase/auth-helpers-react";
import { useUserProfileStore } from "@components/store";
import { Auth, ThemeSupa } from "@supabase/auth-ui-react";
import { AccountSettings } from "@components/account/AccountSettings";
import { TabWrapper } from "@components/TabWrapper";
import { HomeScreen } from "@components/HomeScreen";

export default function Home() {
  return (
    <>
      <Head>
        <title>Some description here</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <TabWrapper>
          <HomeScreen />
        </TabWrapper>
      </Layout>
    </>
  );
}
