import Head from "next/head";
import styles from "../styles/Home.module.css";
import React from "react";
import { Layout } from "@components/Layout";
import { TabWrapper } from "@components/TabWrapper";
import { HomeScreen } from "@components/HomeScreen";

export default function Home() {
  return (
    <>
      <Head>
        <title>Some description here</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <TabWrapper>
          <HomeScreen />
        </TabWrapper>
      </Layout>
    </>
  );
}
